services:

  bedrock-blue:
    build:
      context: .
      args:
        git_url: ${GIT_URL}
    restart: always
    ports:
      - ${BLUE_PORT}:80
    env_file: .env
    volumes:
      - uploads:/var/www/html/bedrock/web/app/uploads
    depends_on:
      - bedrock-db

  bedrock-green:
    build:
      context: .
      args:
        git_url: ${GIT_URL}
    restart: always
    ports:
      - ${GREEN_PORT}:80
    env_file: .env
    volumes:
      - uploads:/var/www/html/bedrock/web/app/uploads
    depends_on:
      - bedrock-db

  bedrock-db:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - bedrock-db:/var/lib/mysql

volumes:
  uploads:
  bedrock-db:



